spring.application.name=reachAI

# JDBC
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/reachai
spring.datasource.username=postgres
spring.datasource.password=262682
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amanagg639@gmail.com
spring.mail.password=hbzzgxwapitlhuvh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

